export const domainRefusalCodes = [
  'INVALID_STATE_TRANSITION',
  'TERMINAL_STATE',
  'ACTION_NOT_EXPIRED',
  'ACTION_EXPIRED',
  'ACTION_TIME_INVALID',
  'ACTION_DIGEST_MISMATCH',
  'POLICY_DECISION_DIGEST_MISMATCH',
  'POLICY_CORE_BINDING_MISMATCH',
  'POLICY_ROUTE_MISMATCH',
  'VERIFICATION_MODE_MISMATCH',
  'ACTION_SUPERSEDE_TOO_LATE',
  'ACTION_CANCEL_TOO_LATE',
  'MANDATE_NOT_ACTIVE',
  'MANDATE_NOT_EXPIRED',
  'MANDATE_TIME_INVALID',
  'MANDATE_CONTAINMENT_FAILED',
  'MANDATE_CAP_EXCEEDED',
  'MANDATE_RESERVATION_CONFLICT',
  'APPROVAL_REQUIREMENT_INVALID',
  'APPROVAL_QUORUM_NOT_MET',
  'ROLE_MISSING',
  'ROLE_UNEXPECTED',
  'ROLE_EXPIRED',
  'ROLE_REVOKED',
  'SUBJECT_NOT_DISTINCT',
  'AGENT_PRINCIPAL_NOT_DISTINCT',
  'ACTION_HUMAN_NOT_DISTINCT',
  'VERIFICATION_REQUIRED',
  'VERIFICATION_MISMATCH',
  'VERIFICATION_UNKNOWN',
  'VERIFICATION_EXPIRED',
  'HCS_AUTHORIZATION_REQUIRED',
  'SETTLEMENT_TRANSACTION_MISMATCH',
  'OBLIGATION_ACTION_CONFLICT',
  'OBLIGATION_ALREADY_SETTLED',
  'PAYMENT_HISTORY_INVALID',
  'ACTION_ALREADY_CONSUMED',
  'REPLAY_DETECTED',
  'INVOICE_ACTION_MISMATCH',
  'INVOICE_REVISION_CONFLICT',
] as const;

export type DomainRefusalCode = (typeof domainRefusalCodes)[number];

export type DomainRefusal = Readonly<{
  code: DomainRefusalCode;
  detail?: string;
}>;
