export const contractIssueCodes = [
  'UNSUPPORTED_SCHEMA_VERSION',
  'UNKNOWN_FIELD',
  'INVALID_IDENTIFIER',
  'INVALID_DIGEST',
  'INVALID_TIMESTAMP',
  'INVALID_DATE',
  'INVALID_INTEGER_ATOMS',
  'INVALID_CAIP_IDENTIFIER',
  'INVALID_ARRAY_ORDER',
  'DUPLICATE_ARRAY_ITEM',
  'AMOUNT_ARITHMETIC_MISMATCH',
  'CROSS_FIELD_MISMATCH',
  'HASH_MISMATCH',
  'UNSUPPORTED_HASH_DOMAIN',
] as const;

export type ContractIssueCode = (typeof contractIssueCodes)[number];
